<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="BLT1227" name="Com.testcase.Amazon_search_testcase" tests="2" failures="0" timestamp="05 Mar 2020 11:49:30 GMT" time="21.395" errors="1">
  <testcase name="move" time="20.638" classname="Com.testcase.Amazon_search_testcase"/>
  <testcase name="close" time="0.757" classname="Com.testcase.Amazon_search_testcase">
    <error type="java.io.IOException" message="Destination &#039;C:\Users\BLTuser.BLT1218\Desktop\New folder\TestFramework\src\test\resources\Screenshot\search.png&#039; directory cannot be created">
      <![CDATA[java.io.IOException: Destination 'C:\Users\BLTuser.BLT1218\Desktop\New folder\TestFramework\src\test\resources\Screenshot\search.png' directory cannot be created
at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:647)
at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:607)
at Com.Baseclass.WrapperClass.screenshot(WrapperClass.java:47)
at Com.testcase.Amazon_search_testcase.close(Amazon_search_testcase.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:214)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- close -->
</testsuite> <!-- Com.testcase.Amazon_search_testcase -->
